#*********************************************************************
#
#  (C) 2001 - 2006 J3d.org
#    http://code.j3d.org/
# 
# Package makefile for the org.j3d.loaders.c3d directory
#
# Author: Justin Couch
# Version: $Revision: 1.1 $
#
#*********************************************************************

PACKAGE = org.j3d.loaders.c3d

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = C3DHeader.java \
  C3DParameter.java \
  C3DStringParameter.java \
  C3DByteParameter.java \
  C3DIntParameter.java \
  C3DFloatParameter.java \
  C3DParameterGroup.java \
  C3DTrajectoryData.java \
  BufferReader.java \
  IntelBufferReader.java \
  MIPSBufferReader.java \
  DECBufferReader.java \
  C3DParser.java \

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = 

# If the package requires extra classes outside the JDK, the JAR files that 
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY =


include ${PROJECT_ROOT}/make/Makefile.jav
