#*********************************************************************
#
#  (C) 2002 Justin Couch
#  http://www.vlc.com.au/~justin/
# 
# Makefile for the j3d.org VFX HMD native library
#
# Author: Justin Couch
# Version: $Revision: 1.1 $
#
#*********************************************************************

# The output library that we want to create
LIBRARY=vfx_hmd

# source files:
C_SOURCE = VFXsdk.c \
	vfx_hmd.c \

# Other libraries that the compile process is dependent on
LIBRARY_3RDPARTY=

include ${PROJECT_ROOT}/make/Makefile.native
