#
# Package makefile for the org.j3d.loaders.ac3d directory
#

PACKAGE = org.j3d.loaders.ac3d

SOURCE = LoaderTokenHandler.java \
  Ac3dLoader.java 

include ${PROJECT_ROOT}/make/Makefile.jav
