#
# Package makefile for the org.j3d.geom.terrain directory
#

PACKAGE = org.j3d.geom.terrain

SOURCE = ElevationGridGenerator.java \
  FractalTerrainGenerator.java \
  ColorRampGenerator.java \
  HeightImageCreator.java \
  HeightDataCreator.java

include ${PROJECT_ROOT}/make/Makefile.jav
