#
# Package makefile for the org.j3d.loaders.ac3d.parser.handlers directory
#

PACKAGE = org.j3d.loaders.ac3d.parser.handlers

SOURCE = Ac3dTokenHandlerBase.java \
  DebugTokenHandler.java \
  ConsoleOutputHandler.java

include ${PROJECT_ROOT}/make/Makefile.jav
