#*********************************************************************
#
#  (C) 2001 Web3d Consortium
#    http://www.web3d.org/
#
# Package makefile for the package org.xj3d.device directory
#
# Author: Alan Hudson
# Version: $Revision: 1.5 $
#
#*********************************************************************

PACKAGE = org.j3d.device.input

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = \
  ButtonModeConstants.java \
  DeviceState.java \
  TrackerState.java \
  GenericHIDState.java \
  GamepadState.java \
  JoystickState.java \
  WheelState.java \
  Tracker.java \
  InputDevice.java \
  ControllerDevice.java \
  TrackerDevice.java \
  MidiDevice.java \
  GamepadDevice.java \
  JoystickDevice.java \
  WheelDevice.java \
  DeviceListener.java \
  DeviceManager.java

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =

# If the package requires extra classes outside the JDK, the JAR files that
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY =

include ${PROJECT_ROOT}/make/Makefile.jav
