#
# Package makefile for the org.j3d.device.input directory
#

PACKAGE = org.j3d.device.input

SOURCE = FileInputSensor.java \
         FileInputDevice.java
 

include ${PROJECT_ROOT}/make/Makefile.jav
