#
# Package makefile for the org.j3d.ui directory
#

PACKAGE = org.j3d.ui

SOURCE = CapturedImageObserver.java \
         ImageCaptureCanvas3D.java \
         LoaderFileFilter.java \
         InputSelectionPanel.java

include ${PROJECT_ROOT}/make/Makefile.jav
