#*********************************************************************
#
#  (C) 2001 J3d.org
# 
#*********************************************************************

PACKAGES = org.j3d.util \
	   org.j3d.util.device \
	   org.j3d.util.interpolator \
	   org.j3d.ui \
	   org.j3d.ui.image \
       org.j3d.geom

NODOC_PACKAGES = \

JARS = j3d-org.jar

JARS_3RDPARTY=

MAIN_CLASS     = 
MAIN_PACKAGE   = 
MAIN_JAR       = j3d-org.jar

#*********************************************************************
#
# Javadoc
#
#*********************************************************************

WINDOWTITLE = 'j3d.org Code Library'
DOCTITLE    = 'j3d.org Code Repository API'
HEADER      = 'j3d.org Code Repository API'
BOTTOM      = '<font size=2>Copyright &copy; 2001 - \
		       <a href=\"http://www.j3d.org\">j3d.org</a> \
               </font>'

include $(PROJECT_ROOT)/make/Makefile.jav 
