#
# Package makefile for the org.j3d.util.device directory
#

PACKAGE = org.j3d.util.device

SOURCE = ErrorOutput.java \
         DeviceDescriptor.java \
         AudioDeviceDescriptor.java \
         InputDeviceDescriptor.java \
         FileLoaderDescriptor.java \
         DynamicClassLoader.java \
         DeviceManager.java

include ${PROJECT_ROOT}/make/Makefile.jav
