#
# Package makefile for the org.j3d.util directory
#

PACKAGE = org.j3d.util.interpolator

SOURCE = Interpolator.java \
         ScalarInterpolator.java \
         PositionInterpolator.java \
		 TestScalarInterpolator.java \
		 TestPositionInterpolator.java

include ${PROJECT_ROOT}/make/Makefile.jav
