#
# Package makefile for the org.j3d.loaders.ac3d.parser.exceptions directory
#

PACKAGE = org.j3d.loaders.ac3d.parser.exceptions

SOURCE = AC3DParseException.java \
  IncompatibleTokenHandlerException.java \
  InvalidTokenOrderingException.java 

include ${PROJECT_ROOT}/make/Makefile.jav
