#
# Package makefile for the org.j3d.geom directory
#

PACKAGE = org.j3d.geom

SOURCE = GeometryData.java \
  UnsupportedTypeException.java \
  InvalidArraySizeException.java \
  GeometryGenerator.java \
  BoxGenerator.java \
  ConeGenerator.java \
  SphereGenerator.java \
  CylinderGenerator.java \
  TorusGenerator.java \
  SpringGenerator.java \
  IntersectionUtils.java \
  Axis.java \
  Box.java \
  Cone.java \
  Cylinder.java \
  Sphere.java \
  Spring.java \
  Torus.java \
  TestBoxGenerator.java \
  TestConeGenerator.java \
  TestCylinderGenerator.java \
  TestSphereGenerator.java \
  TestTorusGenerator.java \
  TestSpringGenerator.java \

#         GIODThickCylinder.java \
#         Knot.java \
#         Mobius.java \
#         Shell.java \
#         Sphere.java \
#         SpiralTorus.java \
#         Spring.java \
#		 MobiusGenerator.java \

#         Torus.java	\

include ${PROJECT_ROOT}/make/Makefile.jav
