#*********************************************************************
#
#  (C) 2001 J3d.org
#    http://code.j3d.org/
# 
# Package makefile for the org.j3d.geom.particle directory
#
# Author: Justin Couch
# Version: $Revision: 1.10 $
#
#*********************************************************************

PACKAGE = org.j3d.geom

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = GeometryData.java \
  UnsupportedTypeException.java \
  InvalidArraySizeException.java \
  CoordinateUtils.java \
  NormalUtils.java \
  GeometryGenerator.java \
  BoxGenerator.java \
  ConeGenerator.java \
  SphereGenerator.java \
  CylinderGenerator.java \
  TorusGenerator.java \
  SpringGenerator.java \
  IntersectionUtils.java \
  Axis.java \
  Box.java \
  Cone.java \
  Cylinder.java \
  Sphere.java \
  Spring.java \
  Torus.java \
  RasterTextLabel.java \
  TestBoxGenerator.java \
  TestConeGenerator.java \
  TestCylinderGenerator.java \
  TestSphereGenerator.java \
  TestTorusGenerator.java \
  TestSpringGenerator.java \

#         GIODThickCylinder.java \
#         Knot.java \
#         Mobius.java \
#         Shell.java \
#         SpiralTorus.java \
#		 MobiusGenerator.java \

#         Torus.java	\

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
# EXTRA = 

# If the package requires extra classes outside the JDK, the JAR files that 
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY =

include ${PROJECT_ROOT}/make/Makefile.jav
