#*********************************************************************
#
#  (C) 2005 Yumetech, Inc
#    http://www.yumetech.com
#
# Author: Russell Dodds
# Version: $Revision: 1.2 $
#
#*********************************************************************

# Names of packages to be compiled. These are declared in the order that
# they are to be compiled in. We create one at a time
BUILD_ORDER = i18n \
  
# Names of packages that we want included in the javadoc
JAVADOC_PACKAGES =
  
# A version number we tack onto the JAR file name for eclipse versioning
# purposes.
JAR_VERSION=2.0.0

# Names of JAR files we want to create
JARS = 

# 3rd party libraries that need including.
JARS_3RDPARTY =

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =	

include $(PROJECT_ROOT)/make/Makefile.config
