#*********************************************************************
#
#  (C) 2005 - 2009 j3d.org 
#    http://www.j3d.org/
#
# Author: Justin Couch
# Version: $Revision: 1.1 $
#
#*********************************************************************

PACKAGE = navigation

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = ButtonAngle.gif \
  ButtonBack.gif \
  ButtonCamera.gif \
  ButtonExamine.gif \
  ButtonFly.gif \
  ButtonFontsize.gif \
  ButtonForward.gif \
  ButtonHome.gif \
  ButtonLandmark.gif \
  ButtonManikin.gif \
  ButtonMeasure.gif \
  ButtonObject.gif \
  ButtonPan.gif \
  ButtonReach.gif \
  ButtonSave.gif \
  ButtonSit.gif \
  ButtonSnapshot.gif \
  ButtonStand.gif \
  ButtonTilt.gif \
  ButtonTool.gif \
  ButtonViewcone.gif \
  ButtonWalk.gif \
  CursorExamine.gif \
  CursorFly.gif \
  CursorObject.gif \
  CursorPan.gif \
  CursorTarget.gif \
  CursorTilt.gif \
  CursorWalk.gif \

include $(PROJECT_ROOT)/make/Makefile.images
