#*********************************************************************
#
#  (C) 2001 J3d.org
#    http://code.j3d.org/
#
# Package makefile for the org.j3d.geom.overlay directory
#
# Author: Justin Couch
# Version: $Revision: 1.1 $
#
#*********************************************************************

PACKAGE = org.j3d.renderer.java3d.overlay

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = \
  UpdatableEntity.java \
  UpdateManager.java \
  ScreenComponent.java \
  Overlay.java \
  InputRequester.java \
  InteractiveOverlay.java \
  AWTEventBehavior.java \
  UpdateControlBehavior.java \
  OverlayManager.java \
  OverlayUtilities.java \
  SubOverlay.java \
  OverlayBase.java \
  InteractiveOverlayBase.java \
  LabelOverlay.java \
  ImageOverlay.java \
  MouseOverlay.java \
  LineData.java \
  LineDetails.java \
  ScribbleOverlay.java \
  ImageButtonOverlay.java \
  TextureOverlay.java \
  InteractiveTextureOverlay.java \
  ScrollEvent.java \
  ScrollEventListener.java \
#  ScrollingOverlay.java \

#  FpsOverlay.java \

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =

# If the package requires extra classes outside the JDK, the JAR files that
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY =	vecmath.jar

include ${PROJECT_ROOT}/make/Makefile.jav
