#*********************************************************************
#
#  (C) 2001 J3d.org
#    http://code.j3d.org/
# 
# Package makefile for the org.j3d.geom.particle directory
#
# Author: Justin Couch
# Version: $Revision: 1.1 $
#
#*********************************************************************

PACKAGE = org.j3d.geom.particle

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = \
	Particle.java \
	ByRefParticle.java \
	PointArrayByRefParticle.java \
	TriangleArrayByRefParticle.java \
	QuadArrayByRefParticle.java \
	MovementFunction.java \
	WindMovementFunction.java \
	GravityMovementFunction.java \
	BoundingBoxMovementFunction.java \
	PickingCollisionMovementFunction.java \
	PlanarCollisionMovementFunction.java \
	PhysicsFunction.java \
	ParticleFactory.java \
	ParticleInitializer.java \
	MaxAgePointEmitter.java \
	ParticleSystem.java \
	ByRefParticleSystem.java \
	PointArrayByRefParticleSystem.java \
	TriangleArrayByRefParticleSystem.java \
	QuadArrayByRefParticleSystem.java \
	ParticleSystemManager.java
    

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = 

# If the package requires extra classes outside the JDK, the JAR files that 
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY =

include ${PROJECT_ROOT}/make/Makefile.jav
