#*********************************************************************
#
#                         (C) 2001-03 j3d.org
#                         http://code.j3d.org/
#
# Package makefile producing j3d-org-geom-particle.jar
# 
# Author: Justin Couch
# Version: $Revision: 1.4 $
#
#*********************************************************************

# No need to put in subdirs here. We only do that if we want to explicitly
# exclude some directory and then we name everything around it.
JAR_CONTENT= org/j3d/geom/particle \

# Manifest file name. Stored in the make/manifest directory
MANIFEST=geom-particle.mf

include ${PROJECT_ROOT}/make/Makefile.jav
