#
# Package makefile for the org.j3d.util directory
#

PACKAGE = org.j3d.util

SOURCE = ErrorHandler.java \
         SAXErrorHandler.java \
         SAXEntityResolver.java	\
		 ImageLoader.java \
		 ColorUtils.java 

include ${PROJECT_ROOT}/make/Makefile.jav
