#
# Package makefile for the org.j3d.ui.image directory
#

PACKAGE = org.j3d.ui.image

SOURCE = JPEGImageObserver.java \
  JPEGSequenceObserver.java

include ${PROJECT_ROOT}/make/Makefile.jav
