#
# Package makefile for the org.j3d.ui.navigation directory
#

PACKAGE = org.j3d.ui.navigation

SOURCE = FrameUpdateListener.java \
    NavigationStateListener.java \
    ViewpointTransition.java \
	NavigationToolbar.java \
	MouseViewHandler.java \
	NavigationStateManager.java

include ${PROJECT_ROOT}/make/Makefile.jav
