#
# Package makefile for the org.j3d.loaders.ac3d.parser directory
#

PACKAGE = org.j3d.loaders.ac3d.parser

SOURCE = OutputHandler.java \
  TokenHandler.java \
  LineTokenizer.java \
  Ac3dParser.java	

include ${PROJECT_ROOT}/make/Makefile.jav
