#*********************************************************************
#
#  (C) 2009 Yumetech, Inc
#    http://www.yumetech.com/
# 
# Package makefile for the internationalisation config directory
#
# Author: Justin Couch
# Version: $Revision: 1.1 $
#
#*********************************************************************

PACKAGE = i18n

# The list of files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = j3dorgResources.properties \

# If the package requires extra classes outside the JDK, the JAR files that 
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY = 

include ${PROJECT_ROOT}/make/Makefile.config
