#
# Package makefile for the org.j3d.loaders.ac3d.models directory
#

PACKAGE = org.j3d.loaders.ac3d.models

SOURCE = Ac3dMaterial.java \
  Ac3dSurface.java \
  Ac3dObject.java

include ${PROJECT_ROOT}/make/Makefile.jav
